version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: rag-qdrant-v1
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: rag-api-v1
    env_file:
      - .env
    environment:
      QDRANT_URL: http://qdrant:6333
    ports:
      - "8000:8000"
    depends_on:
      - qdrant

volumes:
  qdrant_data: